### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by kronik** [sebastienwindal/FRDLivelyButton#6]
Hi! 

Would it be hard for you to add such a popular icons like: share (export), retry (reload) and a checkmark? Appreciate if you could do that. Thanks.

**Comment by sebastienwindal** [comment]
The problem is animating a CGPath to any other CGPath is possible but what I found is that the transition between two CGPaths when they are very different does not look very good. Transforming a horizontal line to a circle for instance does not produce a nice animation.
This is why in the control, I actually use 4 CAShapeLayer (3 lines, 1 circle) and I animate their opacity and path properties individually...
If the new icon can be decomposed in 3 straight lines and circle (without fill) that would be easy to add, a simple ckechmark would be super easy. Anything else would probably be quite a bit of work, especially the more complex paths like the share icon...

**Comment by sebastienwindal** [comment]
This thread offers better insight in what I am trying to say:

http://stackoverflow.com/questions/9513082/cashapelayer-animating-path-glitches-flickers-from-ellipse-to-rect-and-back

**Comment by falaix** [comment]
Would be nice to see that checkmark in an upcoming version!
